app:
  name: "demos"
  env: "local" # local, dev, prod
  jwt:
    jwt_secret: "super-krutoy-secret-key-makar228-please-be-happy"
    access_ttl: 15m # данные в минутах
    refresh_ttl: 168h # данные в часах == 7 дней
storage_path: "postgres://postgres:postgres@localhost/demos?sslmode=disable" # `driver://username:password@addres/database`
server:
  host: "localhost"
  port: "8081"
database:
  driver: "postgres"
  address: "localhost:5432"
  username: "postgres"
  password: "postgres"
  database: "demos"
  sslmode: "disable"